project:
  image: images/

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #  DB Configuration.
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/studentportal
    username: Deep
    password: Deep143@
    driver-class-name: com.mysql.cj.jdbc.Driver

  #  Hibernate Config.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  # Mail Service.
  mail:
    host: smtp.gmail.com
    port: 25
    username: deepkasodariya44@gmail.com
    password: pcjf irja dvca dgch
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# Security Config.
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # A Day
      refresh-token:
        expiration: 604800000 # 7 Days
